### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by jkhoo9290** [sriharshamvs/TelegramUserScraper#5]
Hi sir, thank you very much for your script. I have an issue here. May I know how to solve this?

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\TelegramUserScraper-master\scrapeSingleGroup.py", line 97, in <module>
    main()
  File "C:\Users\Admin\Desktop\TelegramUserScraper-master\scrapeSingleGroup.py", line 15, in main
    client = TelegramClient(phone, api_id, api_hash)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\telegrambaseclient.py", line 302, in __init__
    self._sender = MTProtoSender(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\mtprotosender.py", line 57, in __init__
    self._connect_lock = asyncio.Lock(loop=loop)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 77, in __init__
    super().__init__(loop=loop)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

**Comment by sriharshamvs** [comment]
Hello, This is an issue python version 3.10. 
Python 3.10 deprecates interacting with a non-running event loop.

**Comment by jkhoo9290** [comment]
Issue solved, just need to update the latest telethon
